### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by jackbrannen** [ChasKane/gay-toolbar#1]
It’s installed and enabled on my iPhone… but I can’t find out how to configure or activate it. The only control I have is to edit hotkeys.

**Comment by ChasKane** [comment]
hey @jackbrannen I'm looking into this now; this is my first published plugin and I didn't think about what the initial state would be when installed from the community plugins list 😅

**Comment by ChasKane** [comment]
@jackbrannen this should be fixed now. Lmk if updating the plugin (or if that doesn't work, uninstalling and reinstalling) doesn't work. Keep me posted on how it goes and how using it is  for ya ^.^

**Comment by jackbrannen** [comment]
@ChasKane Got it working after reinstall. This probably isn't for me. UI/UX is too crazy.

**Comment by ChasKane** [comment]
oh interesting, how do you mean crazy? Like what specifically doesn't work for you? It's the only really functional toolbar on the market rn so this surprises me.

**Comment by jacksojourn** [comment]
@ChasKane Hey thanks for pushing back:

1. Don't want to be hurtful
2. I went back and started playing with it some more and maybe this can work for me…

More on my first experience: When I first opened it up the first time, my immediate reaction was "oh man the wild color scheme is on by default." I get the appeal, but personally what I want is something minimal. I also realize some of the buttons are not aligned with the others. So I'd have to change all that. So I go in to edit it and things start jiggling, and there's a wild cursive font in the instructions, and I don't see an easy way to edit the colors (I'm sure it's in the documentation, but to hit so many road blocks so fast is discouraging). Made me think, "I am not the user this is designed for."

Going back in and looking at it again, I did find how to change colors. We're good there. (Side note: would be nice if there were some pre-loaded color schemes like solid black.)

Is there a way to take off the long-press icon? That's where I'm stuck currently.

**Comment by ChasKane** [comment]
Holy cow thanks for your response, this made my morning ^.^ are you interested in pair-coding on these ideas?

A personal note: I *have* noticed I tend to shove my colorfulness in people's faces and I'm still figuring out why and how to proceed. I don't mean to cause harm, but my most life-saving moments and inspirations/people have all encouraged these aspects of me, as well as a certain insistence that people get comfortable with strangeness. But ik there are more and less strategic ways to encourage strangeness if that's my goal.

SO! Let's add:
* a less intense, more tasteful set of defaults -- one with empty buttons so the full suite of features gets showed off immediately on start.
* a way to clear all colors, secondary actions, or buttons at once
* better labeling and organization in the settings (considering a tabbed setup)
  * tbh I hate the default color picker on android so let's use the react library for that
  * add a quick-select palette that doubles as a defaults array for new buttons to randomly select their colors from)
  * instructions 
  * perhaps an option for the jiggling heheh
* no cursive fonts

Of these, only a modified defaults set is mandatory to aid user onboarding for now I think. perhaps a button to clear everything and some instructions in a settings panel. I'll work on that now. Wanna pair on anything else here?

**Comment by ChasKane** [comment]
Also, by "some of the buttons are not aligned with the others" are you referring to how some have just one icon in the center and others have 2 icons? The tiny icon in the top right indicates the button's long-press command. Perhaps this should be highlighted more in the README.

**Comment by yankai19900930** [comment]
"Thank you, author, your plugin is really great, and we are already discussing it within our group."

I've seen a few articles reporting on it. But it seems like everyone in the comments mentioned that there's no unified setting for all colors, and each one has to be set manually, which is a bit difficult.

**Comment by jackbrannen** [comment]
@ChasKane 

> are you interested in pair-coding on these ideas?

I'm not actually a developer, just one of those "power users" who knows just enough to be dangerous. But I'm happy to test and give feedback, if it's helpful.

Of the features you mentioned, I agree the most important one is probably a way to change button color globally, as @yankai19900930 suggested. 

Removing all secondary actions at once would also be nice.

Also, I'm still not clear on how to remove _any_ secondary action or its icon. I like the idea of a secondary action, but I'd prefer to hide the icon for it, as they feel cluttered to me as-is.

(Also also, the preset secondary actions are another area that I think may be a barrier to entry for new users. When someone loads your extension for the first time, how do they know what those secondary actions are? At least 50% of the icons aren't really clear. So they have to test them all manually or edit them all manually.)

> Also, by "some of the buttons are not aligned with the others" are you referring to how some have just one icon in the center and others have 2 icons? The tiny icon in the top right indicates the button's long-press command. Perhaps this should be highlighted more in the README.

No I actually mean the buttons themselves are out of alignment. Couldn't tell if this was an intentional design choice or not. See on the bottom row how the purple paperclip icon and the yellow highlighter icon sit on different baselines?

![Screenshot 2024-12-15 at 1 55 43 PM](https://github.com/user-attachments/assets/f2076bea-ab1c-442c-b5a0-ca4fdb298537)

**Comment by ChasKane** [comment]
I appreciate your power-use then!

I'm working on the button colors issue today -- I've wanted a better color picker for a while, as well as global modifiers as you mention.

To add a secondary action, click on a button with the settings open to view that button's settings. the bottom right button allows you to select a primary action and icon, the top left button is for secondary actions/icons. This will be changing soon so that icons can be selected separately from commands.

Oh my, the alignment thing is very strange. Looks like buttons with secondary actions are behaving differently to those without them. I haven't seen this before... Would you be interested in a live debugging session? I'm not sure I can pin down the issue via text. hmu on whatsapp: +1 (352) 232-7421

**Comment by ChasKane** [comment]
@jackbrannen I fixed the misalignment issue you pointed out, thanks a bunch! Go ahead and update through the obsidian community plugins UI. The latest release (1.1.3) has the fix, as well as a new color picker and the ability to set all button colors at once!

also, to remove secondary actions, the only way currently is to delete the button and make a new one with just the primary action you want.

Unless your customization has come a long way since your screenshot, I'd recommend running the `Gay Toolbar: Load default settings` command -- this is what it'll get you now:

![gay toolbar](https://github.com/user-attachments/assets/8c22bf6f-0613-47be-87ce-b80cedfd2604)
